In [1]:
import pandas as pd

In [2]:
filename = 'abalone.data'

In [3]:
df = pd.DataFrame()

In [4]:
names = [ 'Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight', 'Shell weight', 'Rings']

In [5]:
df_small = pd.read_csv(filename ,names = names, delimiter=',').sample(20)
df_small

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1274   I   0.475     0.360   0.110        0.4920          0.2110   
2991   M   0.595     0.485   0.150        1.0835          0.5305   
1172   M   0.630     0.470   0.155        1.1325          0.5890   
1678   I   0.620     0.485   0.180        1.1540          0.4935   
880    M   0.650     0.525   0.175        1.4715          0.6750   
1237   I   0.375     0.275   0.095        0.2465          0.1100   
2461   F   0.500     0.385   0.130        0.7680          0.2625   
796    M   0.530     0.410   0.155        0.7155          0.2805   
1859   I   0.515     0.415   0.135        0.7125          0.2850   
235    I   0.295     0.225   0.080        0.1240          0.0485   
1096   I   0.475     0.350   0.100        0.4545          0.2165   
3637   I   0.435     0.325   0.100        0.3420          0.1335   
3613   F   0.610     0.490   0.170        1.3475          0.7045   
3339   F   0.585     0.475   0.185        0.8575          0.3465   
2714   I   0.290     0.215   0.065        0.0985          0.0425   
1039   F   0.660     0.475   0.180        1.3695          0.6410   
1521   F   0.680     0.500   0.185        1.7410          0.7665   
1458   I   0.480     0.360   0.125        0.5420          0.2795   
2462   M   0.440     0.325   0.080        0.4130          0.1440   
3151   F   0.665     0.500   0.175        1.7420          0.5950   

      Viscera weight  Shell weight  Rings  
1274          0.1100        0.1500      8  
2991          0.2310        0.2760      8  
1172          0.2110        0.2870      8  
1678          0.2560        0.3150     12  
880           0.3150        0.3990     11  
1237          0.0415        0.0775      6  
2461          0.0950        0.2700     13  
796           0.1685        0.2140     11  
1859          0.1520        0.2450     10  
235           0.0320        0.0400      9  
1096          0.1110        0.1150      7  
3637          0.0835        0.1050      6  
3613          0.2500        0.3045     11  
3339          0.1785        0.2750     12  
2714          0.0210        0.0310      5  
1039          0.2940        0.3350      6  
1521          0.3255        0.4685     12  
1458          0.1025        0.1470      7  
2462          0.1015        0.1300      8  
3151          0.3025        0.7250     21

In [6]:
replace_list = {"Sex" : {"M": 0, "F" : 1, "I": 2}}
df_small.replace(replace_list,inplace=True)

In [7]:
df = pd.read_csv(filename ,names = names, delimiter=',')
del df['Rings']

In [8]:
df.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  
0         0.150  
1         0.070  
2         0.210  
3         0.155  
4         0.055

In [9]:
replace_list = {"Sex" : {"M": 0, "F" : 1, "I": 2}}
df.replace(replace_list,inplace=True)

In [10]:
df.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0    0   0.455     0.365   0.095        0.5140          0.2245   
1    0   0.350     0.265   0.090        0.2255          0.0995   
2    1   0.530     0.420   0.135        0.6770          0.2565   
3    0   0.440     0.365   0.125        0.5160          0.2155   
4    2   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  
0          0.1010         0.150  
1          0.0485         0.070  
2          0.1415         0.210  
3          0.1140         0.155  
4          0.0395         0.055

In [11]:
from sklearn import cluster, datasets, mixture

In [12]:
g = mixture.GaussianMixture(n_components=12)

In [15]:
x = df.iloc[:,:8].values

In [20]:
print(x)

[[0.     0.455  0.365  ... 0.2245 0.101  0.15  ]
 [0.     0.35   0.265  ... 0.0995 0.0485 0.07  ]
 [1.     0.53   0.42   ... 0.2565 0.1415 0.21  ]
 ...
 [0.     0.6    0.475  ... 0.5255 0.2875 0.308 ]
 [1.     0.625  0.485  ... 0.531  0.261  0.296 ]
 [0.     0.71   0.555  ... 0.9455 0.3765 0.495 ]]


In [18]:
df_small.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
1274    2   0.475     0.360   0.110        0.4920          0.2110   
2991    0   0.595     0.485   0.150        1.0835          0.5305   
1172    0   0.630     0.470   0.155        1.1325          0.5890   
1678    2   0.620     0.485   0.180        1.1540          0.4935   
880     0   0.650     0.525   0.175        1.4715          0.6750   

      Viscera weight  Shell weight  Rings  
1274           0.110         0.150      8  
2991           0.231         0.276      8  
1172           0.211         0.287      8  
1678           0.256         0.315     12  
880            0.315         0.399     11

In [16]:
g.fit(x)

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,
        means_init=None, n_components=12, n_init=1, precisions_init=None,
        random_state=None, reg_covar=1e-06, tol=0.001, verbose=0,
        verbose_interval=10, warm_start=False, weights_init=None)

In [19]:
df.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0    0   0.455     0.365   0.095        0.5140          0.2245   
1    0   0.350     0.265   0.090        0.2255          0.0995   
2    1   0.530     0.420   0.135        0.6770          0.2565   
3    0   0.440     0.365   0.125        0.5160          0.2155   
4    2   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  
0          0.1010         0.150  
1          0.0485         0.070  
2          0.1415         0.210  
3          0.1140         0.155  
4          0.0395         0.055

In [32]:
g.predict(x)[0]

10

In [17]:
g.predict_proba(x)[563]

array([0.00000000e+00, 0.00000000e+00, 2.60090374e-01, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.19620520e-07, 2.33234756e-03,
       0.00000000e+00, 0.00000000e+00, 7.37577159e-01, 0.00000000e+00])

In [40]:
clusters_small = g.predict_proba(df_small.iloc[:,:8])
rings_small = df_small['Rings']

In [29]:
g.score(x)

19.727429831163363

In [42]:
¨å+pclusters_small[2]

array([0.00000000e+00, 0.00000000e+00, 5.60755581e-10, 0.00000000e+00,
       5.53411343e-03, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.94465886e-01])

In [58]:
pd.get_dummies(rings_small).head()

4   6   7   8   9   10  11  12  13
3721   0   0   0   0   1   0   0   0   0
1133   0   0   0   0   1   0   0   0   0
927    0   0   0   1   0   0   0   0   0
2626   1   0   0   0   0   0   0   0   0
2059   0   0   0   1   0   0   0   0   0

In [69]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

In [71]:
cluster_age = clusters_small.T @ pd.get_dummies(rings_small)
cluster_age = cluster_age / cluster_age.sum(1)[:,None]
cluster_age

array([[0.   , 0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.103, 0.   , 0.   , 0.897, 0.   ],
       [0.251, 0.251, 0.251, 0.246, 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.019, 0.   , 0.247, 0.   , 0.   , 0.735],
       [0.   , 0.615, 0.   , 0.004, 0.001, 0.26 , 0.   , 0.   , 0.119],
       [0.   , 0.   , 0.   , 0.   , 0.397, 0.   , 0.405, 0.197, 0.   ],
       [0.   , 0.   , 0.   , 0.353, 0.   , 0.613, 0.   , 0.   , 0.033],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.008, 0.006, 0.986],
       [0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.645, 0.   , 0.016, 0.002, 0.337],
       [0.   , 0.   , 0.   , 0.   , 0.682, 0.   , 0.   , 0.318, 0.   ],
       [0.   , 0.   , 0.185, 0.373, 0.185, 0.107, 0.   , 0.   , 0.149]])

In [79]:
predicted_classes = g.predict_proba(x) @ cluster_age
predicted_classes[:3]

array([[0.   , 0.   , 0.   , 0.   , 0.653, 0.   , 0.   , 0.347, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.352, 0.   , 0.612, 0.   , 0.   , 0.036]])

In [80]:
age_labels = np.array(pd.get_dummies(rings_small).columns)
age_labels

array([ 4,  6,  7,  8,  9, 10, 11, 12, 13], dtype=int64)

In [81]:
predicted_age = predicted_classes @ age_labels
predicted_age.shape

(4177,)

In [82]:
predicted_age[:5]

array([10.04 ,  9.001,  9.404,  9.974,  6.243])